// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/books/:collection": {
    params: {
      "collection": string;
    };
  };
  "/movies": {
    params: {};
  };
  "/books": {
    params: {};
  };
  "/api/lotr": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/about": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/books/:collection" | "/movies" | "/books" | "/api/lotr" | "/contact" | "/about";
  };
  "routes/books.$collection.jsx": {
    id: "routes/books.$collection";
    page: "/books/:collection";
  };
  "routes/movies._index.jsx": {
    id: "routes/movies._index";
    page: "/movies";
  };
  "routes/books._index.jsx": {
    id: "routes/books._index";
    page: "/books";
  };
  "routes/api.lotr.tsx": {
    id: "routes/api.lotr";
    page: "/api/lotr";
  };
  "routes/contact.jsx": {
    id: "routes/contact";
    page: "/contact";
  };
  "routes/_index.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/about.jsx": {
    id: "routes/about";
    page: "/about";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/books.$collection": typeof import("./app/routes/books.$collection.jsx");
  "routes/movies._index": typeof import("./app/routes/movies._index.jsx");
  "routes/books._index": typeof import("./app/routes/books._index.jsx");
  "routes/api.lotr": typeof import("./app/routes/api.lotr.tsx");
  "routes/contact": typeof import("./app/routes/contact.jsx");
  "routes/_index": typeof import("./app/routes/_index.jsx");
  "routes/about": typeof import("./app/routes/about.jsx");
};