// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/api/lotr": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/about": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/api/lotr" | "/contact" | "/about";
  };
  "routes/api.lotr.tsx": {
    id: "routes/api.lotr";
    page: "/api/lotr";
  };
  "routes/contact.jsx": {
    id: "routes/contact";
    page: "/contact";
  };
  "routes/_index.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/about.jsx": {
    id: "routes/about";
    page: "/about";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/api.lotr": typeof import("./app/routes/api.lotr.tsx");
  "routes/contact": typeof import("./app/routes/contact.jsx");
  "routes/_index": typeof import("./app/routes/_index.jsx");
  "routes/about": typeof import("./app/routes/about.jsx");
};